### ISSUE TITLE
Seems to break Light Level Overlays

### ISSUE THREAD

**Issue by Hexblood** [jaredlll08/Ambient-Environment#1]
Minecraft version: 1.12.2
Forge version: 14.23.5.2836
Ambient Environment version: 1.0.1

## Issue:
When installed with mods like More Overlays or NEI and their Light Level Overlay is activated with a light source present the Overlay gets greyed out and looses a portion of it's functionality. Removing Ambient Environment fixed the issue. 

Issue was noticed at day and night on the surface of the world and happened with a few different modded light sources including Silent's Gems Glowing Roses.

**Comment by jaredlll08** [comment]
I can't seem to reproduce.

working fine with NEI
![image](https://user-images.githubusercontent.com/5553605/57183388-a9942780-6eac-11e9-89bd-cfa03e514f32.png)

And working fine with Light Level Overlay
![image](https://user-images.githubusercontent.com/5553605/57183408-02fc5680-6ead-11e9-9b15-6758d0fe9d4f.png)
