### ISSUE TITLE
Does not respect SemVer ?

### ISSUE THREAD

**Issue by Raavea** [jaredlll08/Ambient-Environment#14]
Hi there,
 I'm (slowly) trying to put together a modpack for 1.17 using the Fabric launcher, and I'm getting a lot of warnings and errors, not all of which I understand, so I thought I'd start at the top and just work my way down.

 Your mod, amongst others, doesn't cause any crashing, so that's all good! But it does produce this warning:

`[main/WARN]: Mod ambientenvironment (fabric-1.17-rc2-6.0.0.11) does not respect SemVer - comparison support is limited.`

Is this something I've configured incorrectly, or something you can fix?
 Sorry, I'm a big noob when it comes to creating modpacks, or github - I think this is how you're supposed to ask mod authors things about their code? Apologies if this is wrong .__.'

**Comment by jaredlll08** [comment]
This isn't an error that you need to worry about, it is just how I have decided to version my mod.
