### ISSUE TITLE
Issue when visiting Vibrant Journeys prairies

### ISSUE THREAD

**Issue by Laike-Endaril** [jaredlll08/Ambient-Environment#2]
Easier seen than explained, so here are screenshots:
[With Ambient Environment installed](https://ibb.co/gdwSYdR)
[Without](https://ibb.co/YXXtTQ1)

You may notice the Ancient Warfare structure there, but in another MC instance I found the same issue with only Ambient Environment, Project Vibrant Journeys, and Nature's Compass (to find a prairie quickly) installed.

Color value overflow?  Not sure.  Otherwise, loving the mod

**Comment by AssaultSquid** [comment]
same issue with biomes o' plenty Orchards

**Comment by jaredlll08** [comment]
Should be fixed in latest versions :)
