### ISSUE TITLE
Incompatibility with bedrock waters

### ISSUE THREAD

**Issue by ghost** [jaredlll08/Ambient-Environment#24]
When using the Bedrock Waters mod, the water loses nois
![2022-01-17_17 53 58](https://user-images.githubusercontent.com/80956290/149792772-f878910f-ff0f-4836-9861-22f9c901c8fd.png)
![2022-01-17_17 58 44](https://user-images.githubusercontent.com/80956290/149792776-cb8493ce-a51c-40db-98ac-6d2c29e13d75.png)
e

**Comment by jaredlll08** [comment]
I'm a bit confused, I already apply noise to the water?

I do use the same algorithm (with different values) as I do on the grass though, so it may not be as noticeable

**Comment by ghost** [comment]
Noise was not shown from the bedrock waters mod
I will rename the problem as incompatibility with bedrock waters
When used with bedrock waters
Water loses noise and becomes plain

**Comment by jaredlll08** [comment]
This has been fixed for 1.18, unfortunately I don't think I am going to make a release for 1.17.
