### ISSUE TITLE
Could you upload this to modrinth?

### ISSUE THREAD

**Issue by intergrav** [jaredlll08/Ambient-Environment#28]
It would really help as I dont think you can put curseforge mods into a modrinth modpack, and people seem to be moving over

**Comment by jaredlll08** [comment]
I currently have no interest in my mods being uploaded to Modrinth.

My files are already available to third parties via the CurseForge API.

**Comment by intergrav** [comment]
Oh okay, I did not know that. Thanks!

**Comment by jaredlll08** [comment]
https://modrinth.com/user/jaredlll08

**Comment by intergrav** [comment]
Awesome! :D
