### ISSUE TITLE
Add mod to Modrinth

### ISSUE THREAD

**Issue by forditt** [jaredlll08/Ambient-Environment#35]
Please add mod to [Modrinth](https://modrinth.com/mods). I'm used to using this site, but your mod is the only one missing from my modpack on this site 🐢
![зображення](https://user-images.githubusercontent.com/105544922/227735769-a68eb363-9915-4fc7-8335-e8290c21ee4e.png)

**Comment by sisby-folk** [comment]
This would be helpful! it's a nice small mod and it's on our shortlist of stuff that isn't on modrinth proper just yet.

**Comment by jaredlll08** [comment]
https://modrinth.com/user/jaredlll08

**Comment by forditt** [comment]
> https://modrinth.com/user/jaredlll08

thank you
