### ISSUE TITLE
Incompatible with Sodium 0.5.0 and 0.5.1

### ISSUE THREAD

**Issue by MrAnvil935** [jaredlll08/Ambient-Environment#39]
Sodium 0.4.10
![2023-08-15_21 45 21](https://github.com/jaredlll08/Ambient-Environment/assets/71383587/f4575189-9fa8-4165-a1c1-0a41df3128f2)
Sodium 0.5.0 (same result in 0.5.1)
![2023-08-15_21 43 52](https://github.com/jaredlll08/Ambient-Environment/assets/71383587/5443284b-1807-4953-9da4-741ff4b5255f)

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/Ambient-Environment/issues/36#issuecomment-1535240433
