### ISSUE TITLE
[1.14.4] Issue with tree colors

### ISSUE THREAD

**Issue by Gbergz** [jaredlll08/Ambient-Environment#4]
Hello! I'm having an issue with the tree colors being darker than usual, and it's true i removed the mod and all colors went back to normal. Could be mods interfering as i haven't tried the mod on an instance only with it.

**Without the mod:**
[Imgur1](https://i.imgur.com/y8zqdym.jpg)

**With the mod:**
[Imgur2](https://i.imgur.com/f16LsjJ.jpg)

Open both links and compare the 2, switch between the tabs.

MC: 1.14.4
Forge: 28.0.104
Mod Version: 2.0.0

EDIT: Or is this intended? Some leaves aren't affected by this. Seems to only be oak and maybe some  other leaves.

**Comment by jaredlll08** [comment]
Yip, this is an intended feature, it happens with water as well, granted the foliage colours are set to be the darkest, I can tike it down a bit
