### ISSUE TITLE
Grid-like leaves patern and "Better Leaves Add-on" compatibility.

### ISSUE THREAD

**Issue by NFRNS** [jaredlll08/Ambient-Environment#8]
I will just repost my massage from curseforge here:

"Hey Jared, thank you for this mod) But let me ask if its possible to add config option to disable leaves changeing separetly fromm grass? I got some realy wierd chess-grid patern on them (grass is fine tho).. but when i started using "[Better Leaves Add-on](https://www.curseforge.com/minecraft/texture-packs/better-leaves-add-on-2-0)" it completly disabled your mod for some reason.. is there any way to make them work together? (thats why i thought disabling mod leaves dependence may help to avoid grass affection)"

**Comment by katubug** [comment]
I would also like this, but just for picky aesthetic reasons :P

**Comment by NFRNS** [comment]
Wait, nevermind about "Better Leaves Add-on", i got back to the game to make screenshots of "patern" i was talking about, tested all combination of texture-packs i used, and for some reason i dont have "mod is not working with~" problem anymore. 
But still, heres heres ss of what i was talking about: 

![Base Profile Screenshot 2019 10 25 - 20 11 33 46](https://user-images.githubusercontent.com/57009034/67591372-f1ae4b80-f765-11e9-8191-6a4ac63eb7e8.png)

Was it suposed to be like this or is it a bug? I mean realy dark leaf blocks right next to realy light leaf blocks, or maybe I enabled/disabled something in OptiFine? Pine and Spruce are uneffected. Well, being able to "turn leaves off" in mod config still wuld be a neat feachure) (its not that bad on ss, usualy its more agressive :)

![Base Profile Screenshot 2019 10 25 - 20 42 59 08](https://user-images.githubusercontent.com/57009034/67592387-405ce500-f768-11e9-96be-cb30a3cada59.png)

Looks like some leaves became completely black.

**Comment by jaredlll08** [comment]
I just removed the foliage changes, so use the latest version
